/**
 * Server-side OTP verification for signup Step 1.
 *
 * This route verifies the 6-digit code that Supabase sends via email when
 * signInWithOtp() is called. Unlike the magic link / PKCE redirect flow,
 * this approach has ZERO browser dependency — the user can read the code
 * from any device or browser and enter it here.
 *
 * IMPORTANT — Supabase Email Template Requirement:
 * The "Magic Link" email template (Supabase Dashboard > Authentication >
 * Email Templates > Magic Link) MUST include {{ .Token }} to display the
 * 6-digit code. Example:
 *
 *   Your ServiceDraft AI verification code is: {{ .Token }}
 *   Enter this code on the signup page to verify your email.
 *   Or click this link to verify (same browser only): {{ .ConfirmationURL }}
 */
import { NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';

export async function POST(request: Request) {
  try {
    const { email, token } = await request.json();

    if (!email || !token) {
      return NextResponse.json(
        { error: 'Email and verification code are required' },
        { status: 400 }
      );
    }

    // Sanitize: strip whitespace, ensure digits only (Supabase OTP length is configurable)
    const cleanToken = token.replace(/\s/g, '');
    if (!/^\d{6,8}$/.test(cleanToken)) {
      return NextResponse.json(
        { error: 'Verification code must be 6-8 digits' },
        { status: 400 }
      );
    }

    const supabase = await createClient();

    // verifyOtp with type 'email' validates the 6-digit code generated by signInWithOtp().
    // On success, it creates a session and the SSR library sets session cookies
    // via the setAll() callback in src/lib/supabase/server.ts.
    const { data, error } = await supabase.auth.verifyOtp({
      email,
      token: cleanToken,
      type: 'email',
    });

    if (error) {
      console.error('[verify-otp] Verification failed:', error.message);

      // Map Supabase error messages to user-friendly text
      const msg = error.message.toLowerCase();
      if (msg.includes('expired') || msg.includes('otp has expired')) {
        return NextResponse.json(
          { error: 'Code expired. Please request a new one.' },
          { status: 400 }
        );
      }
      if (msg.includes('invalid') || msg.includes('token')) {
        return NextResponse.json(
          { error: 'Invalid code. Please check and try again.' },
          { status: 400 }
        );
      }
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    if (!data.session) {
      console.error('[verify-otp] No session returned after successful verification');
      return NextResponse.json(
        { error: 'Verification succeeded but no session was created. Please try again.' },
        { status: 500 }
      );
    }

    return NextResponse.json({ success: true, userId: data.user?.id });
  } catch (err) {
    console.error('[verify-otp] Unexpected error:', err);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}
